tasks:
  build:
    name: Build
    description: Clean build the project and run on port 8080
    command: |
      ./gradlew bootRun
    triggeredBy:
      - manual

  test:
    name: Test
    description: Run the test suite of the project
    command: |
      ./gradlew test
    triggeredBy:
      - manual

  format:
    name: Format
    description: Format the Java files in the project
    command: |
      ./gradlew spotlessJavaApply
    triggeredBy:
      - manual

  seed-tags:
    name: Seed Tags
    description: Seed the database with sample tags
    command: |
      ./seed-tags.sh
    triggeredBy:
      - manual

services:
  server:
    name: Server
    description: Serve the RealWorld Example App on port 8080
    commands:
      start: |
        ./gradlew bootRun
      ready: |
        curl http://localhost:8080/tags -s -f -o /dev/null && gitpod environment port open 8080 --name "RealWorld App"
      stop: |
        ./gradlew --stop
        gitpod environment port close 8080
    triggeredBy:
      - postEnvironmentStart
